name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-sonarqube:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install Python dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-cov httpx

      # 4. Set PYTHONPATH
      - run: echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      # 5. Run pytest with coverage
      - run: pytest --cov=src --cov-branch --cov-report=xml

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - run: docker build -t fastapi-calculator .

      # 7. Run Docker container on shared network
      - run: |
          docker network create zapnet
          docker run -d --network zapnet --name fastapi-app fastapi-calculator
          sleep 20  # wait for app to start

      # 8. Run OWASP ZAP baseline scan
      - run: |
          mkdir zap-output
          chmod 777 zap-output 
          docker run --rm --network zapnet \
          -v $(pwd)/zap-output:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          /zap/zap-baseline.py \
          -t http://fastapi-app:8000 \
          --autooff \
          -I \
          -x zap-report.xml \
          -r zap-report.html \
          -J zap-report.json \
          -w zap-warnings.md




      # 9. Upload ZAP report
      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/*


      # 10. SonarQube scan
      - uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.python.coverage.reportPaths=./coverage.xml
