name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Unit Tests + SonarQube
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube scan

      # Step 2: Run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          pip install pytest flask pytest-cov
          python -m pytest src/test.py --cov=. --cov-report xml:coverage.xml


 # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectKey: sonarqube_python
          organization: ziegen28
          sources: src
          coverageReportPaths: coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
